### PR TITLE
Update MarkdownEditor.php

### PR DESCRIPTION
**Pull request by albertobenavides**
Replaced with RichEditor from filamentphp

### CODE REVIEW

**Comment by atmonshi** [comment]
Thank you :) 
However, some are still using the markdown editor. Are there any issues with it to replace it?

you can add a [new editor](https://larazeus.com/docs/sky/v3/configuration#content-adding-new-editor) to your app or submit a new PR :)

**Comment by albertobenavides** [comment]
Hello :) The Markdown Editor is not compatible for filament 3. Thats why I have update and use the one in filament.

**Comment by albertobenavides** [comment]
I know we can add a new editor, but I like the simple markdown editor for most of purposes.

**Comment by albertobenavides** [comment]
@atmonshi, I am using rich-editor without a problem. But, as you stated, I think having both options is better

WhyNotBothTakeBothGIF

**Comment by atmonshi** [comment]
Using it for a new project won't affect a thing, but when someone upgrades the old posts won't rendered correctly either on the editor admin page or on the FE :)
it all comes down to how the markup is stored in the DB, markdown or HTML.

**Comment by albertobenavides** [comment]
> Using it for a new project won't affect a thing, but when someone upgrades the old posts won't rendered correctly either on the editor admin page or on the FE :) it all comes down to how the markup is stored in the DB, markdown or HTML.

Oh, I get what you said, but you can always use {!! !!} to render HTML in Laravel apps. So that should not be a problem at all.

**Comment by atmonshi** [comment]
> you can always use {!! $some_html !!} to render HTML in Laravel

yes I know :), but we also have `parsers` and `skipper` it's not just the content. anyway, will work on this and release it with v3.1 soon


thank you again :).

**Comment by albertobenavides** [comment]
Thank you! Keep the good work going. I'll try to help any time I can :B

**Pull request merged**
