### PR TITLE
introduce ability to filter posts by category

### PR DESCRIPTION
**Pull request by thyseus**

### CODE REVIEW

**Comment by atmonshi** [comment]
thank you so much

**Comment by atmonshi** [comment]
how the search will be applied from the UI? 
how are you showing the categories list to the user
since the categories list already in the left

**Comment by thyseus** [comment]
@atmonshi 
I dont understand your question. For me it _either_ `?category=` _or_ `?search=`, not both at the same time. It works fine now for our use case.

**Comment by atmonshi** [comment]
that's perfect 
curious tho, are you using the default theme, or are you using `sky` as headless and creating your own theme?

**Comment by thyseus** [comment]
Sounds weird, but we use kind of "both" :) The content that is managed in our company has several other applications accessing them with each of their own theme. We have choosen lara-zeus sky because of the filament integration (where we have everything else integrated also) and because it is so lightweight !

**Pull request merged**
